version: '3.7'
services:
    app:
        image: rust_develop_env
        build:
            context: .
            dockerfile: Dockerfile
            target: develop_env
        volumes:
            - .:/usr/src/app
            - ~/.vim:/root/.vim:ro
        ports:
            - "8000:8000"
        networks:
            - rust
        user: "1000:1000"
        command: ./installandrun.sh
networks:
    rust:
