version: '3.7'
services:
    app:
        image: test
        build:
            context: .
            dockerfile: Dockerfile
            target: develop_env
        volumes:
            - .:/usr/src/app
            - /usr/src/app/target/
            - ~/.vim:/root/.vim:ro
        ports:
            - "8000:8000"
        networks:
            - rust
        command: ./installandrun.sh
networks:
    rust:
